import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/composition/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col  items-center p-10 pt-20">
          <div className="max-w-screen-2xl w-full">
            <Header />
            <div className="mt-36 flex justify-center flex-col gap-4 px-96 ">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
